### ISSUE TITLE
`mainDefinition` Field Yield Error when Mining. `"Template render error for {selection-text}"`

### ISSUE THREAD

**Issue by deppfellow** [rudnam/JP-study#10]
Hey man, thanks for the Note Type. However, I have slight issue on `mainDefinition` field when doing mining. Following all your `README` exactly, including the Yomichan's field and handlebar, it yield following error:

```
ExtensionError: The partial selection-text could not be found
    at ElasticHandlebarsVisitor.invokePartial (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/lib/handlebars.js:6140:13)
    at ElasticHandlebarsVisitor.PartialStatement (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/lib/handlebars.js:5887:10)
    at ElasticHandlebarsVisitor.accept (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/lib/handlebars.js:1976:36)
    at ElasticHandlebarsVisitor.acceptKey (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/lib/handlebars.js:1937:26)
    at ElasticHandlebarsVisitor.acceptArray (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/lib/handlebars.js:1957:16)
    at ElasticHandlebarsVisitor.Program (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/lib/handlebars.js:1985:14)
    at ElasticHandlebarsVisitor.Program (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/lib/handlebars.js:5877:11)
    at ElasticHandlebarsVisitor.accept (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/lib/handlebars.js:1976:36)
    at ElasticHandlebarsVisitor.resolveNodes (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/lib/handlebars.js:6285:12)
    at prog (chrome-extension://likgccmbimhjbgkjambclfkhldnlhbnn/lib/handlebars.js:6240:27)

message: "Template render error for {selection-text}"
```

I guess there is something wrong with my handlebar? My handlebar is just Yomichan's default with your `{selection-text-modified}`, `{grammar-pt}`, and `{context}` below the default Yomichan's

![image](https://github.com/user-attachments/assets/877d2726-7a05-4ba8-8a70-c9331d0d1274)
![image](https://github.com/user-attachments/assets/5d00ab01-90cf-405f-b9ba-a52bb682f13b)

Thanks in advance

**Comment by rudnam** [comment]
There's been a lot of updates with yomitan since I made this template so apparently `{selection-text}` doesn't work anymore. Try replacing it with `{popup-selection-text}`

**Comment by deppfellow** [comment]
Nice, changing `mainDefinition` value to `{popup-selection-text}` make it worked now. Thanks a lot
